/**
 * PRISM v11 — Service Worker
 * Cache-first strategy for app shell · All JS inlined in HTML
 *
 * Strategy:
 *   App shell (HTML, manifest, icons, fonts) → cache-first, then network fallback
 *   API calls / live telemetry              → network-only (never cached)
 *   Offline mutations                        → queued in IndexedDB by the app
 */

const CACHE_VERSION   = 'prism-v11-v15'; // v15: Forecast-in-Finance MOBILE redesign (follow-up to v14's sidebar retirement, driven by real-device feedback that the moved content "cannot be seen or optimally used on mobile"): .fh-sec gains scroll-margin-top so PRISM_openForecasting/navigateKpi deep links stop landing under the fixed nav+site-ctx chrome (the literal cannot-be-seen failure); a live outcome strip (#fh-inputs-live — NPV/IRR/payback/annual-net, written by renderSidebar on every runCalc) sits directly above the Global Defaults inputs so cause->effect is visible on a phone; the collapsed "Forecast Inputs & Programs" header now publishes a live summary (fh-sum-inputs); a WACC range slider (#g-wacc-slider) pairs with the number input through the same g->f mirror; the Investment Case section boots collapsed on <=768px so the section headers read as a table of contents; and a late <style id="prism-fhmobile-css"> unbreaks the hero tiles at phone width (labels/captions wrap instead of ellipsizing) + upsizes the sidebar-era 9-10px type. Shell-visible HTML change, no new precached asset. Navigations are network-first so an online installed client picks this up regardless; the bump keeps a long-offline client's stale shell from serving the illegible mobile layout. // v14: the forecasting sidebar is retired — its financial forecast content (Portfolio Overview / Non-Dollar strips, Programs by Robot Type, Global Defaults inputs) moved into the Finance view (new "Forecast Inputs & Programs" accordion section `fh-sec-inputs` + live strips inside #finance-sidebar-embed, same element ids so renderSidebar()/syncFinancial() are untouched). Shell-visible HTML change: #sidebar, #sb-toggle and #sb-overlay markup removed, #main is full-width, the hamburger "Forecasting & Global Inputs" entry now deep-links to Finance via the rewired PRISM_openForecasting(). Navigations are network-first so an online installed client picks this up regardless; the bump keeps a long-offline client's stale cached shell from resurrecting the removed sidebar (whose toggle functions are now null-guarded no-ops for exactly that stale-shell case). // v13: Enterprise Readiness E2b - the generated frontend-contract block (a new inline <script>) plus contract validation wired into apiFetch() and the SSE onEvent() handler, and the version badge's honest dropped-update counter. Shell-visible HTML change with no new precached asset (the contract block is inline, like every other module). // v12: Asset Intelligence — the `assets` module key granted to the `core` tier (migration 038) plus a REAL public-demo fixture inside `v11 module: assets` (generated by scripts/gen-demo-asset-plans.ts from the actual derivePlan()/knowledge packs, spliced between the ASET-DEMO-FIXTURE-BEGIN/END markers, ~23KB inline). Shell-visible: the Assets nav entry now appears in the backendless demo (the forced-Core entitlement mirror gained 'assets' to match what the core tier really grants server-side), and the view renders six sample assets with real OSHA receipts instead of an empty sign-in panel. Also two shipped-code fixes in the same module (renderGapEditor's Save now requires a session, not just a role; the registry's class cell no longer prints a duplicated '(forklift) (forklift)'). No new precached asset — the fixture is inline like every other v11 module. Navigations are network-first so an online installed client picks this up regardless; the bump keeps a long-offline client's stale shell from showing the empty demo panel after everyone else sees the real one. // v11: MERGE (claude/prism-asset-schema-maintenance-63n7jk x origin/main) — reconciles two shell-visible histories that both independently bumped v8->v9 with DIFFERENT payloads under the same literal 'v9' label (this branch's v9 = Asset Intelligence A1; origin/main's v9 = Enterprise Readiness E0a+E1a+E1c+E0d — the two v9 payloads never coexisted in either branch's own history, only in this merge). This branch also went on to v10 (Asset Intelligence A2). This v11 bump is the first cache version that actually serves ALL of those shell-visible changes together, so an already-installed, long-offline PWA client's stale cached shell can't keep missing any of them once it regains connectivity. Navigations are network-first, so an online client already has everything regardless; see the v10/v9/v8/v7 entries below for what each prior bump covered on its own. // v10: Asset Intelligence A2 — the asset-list import lane (v11 module: assetimport). New "↪ Import assets" launcher + `#aim-modal-back` overlay injected into the existing #view-assets shell (grep `v11 module: assetimport`), plus a widened `CODE_COPY` map inside the pre-existing `v11 module: assets` IIFE. Shell-visible HTML change (new markup + a new top-level module); navigations are network-first so an online installed client picks it up regardless, but the bump keeps a long-offline client's cached shell from missing the new import button/overlay after others see it. // v9 [this lineage — Asset Intelligence A1]: Asset Intelligence A1 — new #view-assets + nav entries (v11 module: assets). Shell-visible HTML change (new markup, nav buttons, VIEW_MODULE entry); navigations are network-first so online installed clients pick it up regardless, but the bump keeps a long-offline client's cached shell from missing the new nav entry after others see it. // v9 [origin/main lineage, reconciled by the v11 merge below — Enterprise Readiness E0a+E1a+E1c+E0d]: PRISM Enterprise Readiness E0a + E1a. E1a — SSO fragment consumption (consumeSsoFragment(), see PRISM-v10-complete.html's boot handler): a completed SAML login previously landed back on a dead, token-bearing URL fragment with the login modal still up, so SAML SSO had never produced a working browser session. E0a — bulk fleet import modal (v11 module: fleetimport) plus the "Import a manifest file" line in the onboarding wizard's step 5. E1c — the ambiguity-triggered org picker on the login path (CD-4): a non-subdomain login whose email matches more than one org now renders a selector instead of failing. E0d — the "Live, not yet surveyed" tray on the Site Map, listing robots PRISM knows about that have no surveyed floorplan position (rendered OUTSIDE #smap-wrap, deliberately never plotted as a marker). All four are shell-visible HTML changes with no new precached asset (both modules are inline, same as every other v11 module). Navigations are network-first, so an online installed client picks either up regardless; the bump exists so a long-offline client's stale cached shell can't keep serving the old behaviour once it regains connectivity. NOTE: E0a and E1a were developed in parallel and each independently bumped v8->v9; this is the single collapsed v9 entry covering both. // v8: responsive nav — "More ▾" overflow for the top tab strip (v11 module: navmore). Shell-visible HTML change; navigations are network-first so online installed clients pick it up regardless, but the bump keeps a long-offline client's cached shell from resurrecting the invisible-scroll nav after others see the fix. // v7: PRISM Cortex E2E CX4+CX5 retrain to 0.3.0 (docs/CORTEX-E2E-CX4-CX5-PLAN.md §8/Q4/SF-10) — the install handler precaches the model bundle by resolving filenames out of ledger.json (below), and those filenames changed (0.2.0 -> 0.3.0), so an already-installed PWA would otherwise keep serving the stale cached ledger.json + ONNX forever with no invalidation path. Required, and correctly placed here (commit 4) rather than the prior frontend-only commit — navigations are network-first (see below), so that HTML-only change already reached an online installed client with no bump; this artifact change is the one that needed it. Cost: `activate` purges the whole versioned cache, forcing a re-download of the ~11.3MB cortex/runtime/* WASM bundle that did NOT change. (The W6 comment "W2/W5 must not bump again" was wave-scoped to that completion wave, not a standing prohibition — this is a genuinely new shell-visible change.) Bump on any shell-visible change so the activate handler purges the stale shell cache and skipWaiting/clients.claim serve the fresh one.
const SHELL_CACHE     = `${CACHE_VERSION}-shell`;
const DATA_CACHE      = `${CACHE_VERSION}-data`;

// Files that make up the app shell (all JS is now inlined in the HTML)
const SHELL_ASSETS = [
  './',
  './PRISM-v10-complete.html',
  './manifest.json',
  './icon-192.png',
  './icon-512.png',
  // Google Fonts — cached so app works offline with correct typography
  'https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400&family=Syne:wght@400;600;700;800&display=swap',
];

// PRISM Cortex (v11 module: cortex, docs/CORTEX-DESIGN.md §4 P3) — the model bundle
// (src/routes/frontend.ts's `cortex/model/*`) and onnxruntime-web WASM runtime
// (`cortex/runtime/*`) so demo/offline mode gets the REAL in-browser model, not just the
// keyword-rules fallback. Filenames are version-pinned by ledger.json / runtime-manifest.json
// (docs/CORTEX-DESIGN.md D2) — hardcoding them here would silently go stale on a model/runtime
// bump, so fetch the two small manifests at install time and precache whatever they currently
// reference instead. Best-effort: a manifest fetch failure (offline first install, or the
// static Pages mirror not having copied them yet) just means Cortex caches lazily on first use
// via the generic cache-first fetch handler below, same as any other same-origin resource —
// never blocks the rest of the app shell from installing.
async function cortexAssetUrls() {
  const urls = ['./cortex/model/ledger.json', './cortex/runtime/runtime-manifest.json'];
  try {
    const ledger = await (await fetch('./cortex/model/ledger.json')).json();
    urls.push(
      `./cortex/model/${ledger.onnx.file}`,
      `./cortex/model/${ledger.tokenizer.file}`,
      `./cortex/model/${ledger.labels.file}`,
    );
  } catch (err) {
    console.warn('[PRISM SW] Cortex model manifest fetch failed (will cache on first use):', err.message);
  }
  try {
    const runtime = await (await fetch('./cortex/runtime/runtime-manifest.json')).json();
    urls.push(
      `./cortex/runtime/${runtime.entry.file}`,
      `./cortex/runtime/${runtime.loader.file}`,
      `./cortex/runtime/${runtime.wasm.file}`,
    );
  } catch (err) {
    console.warn('[PRISM SW] Cortex runtime manifest fetch failed (will cache on first use):', err.message);
  }
  return urls;
}

// Routes that should NEVER be served from cache (live robot data, auth)
const NETWORK_ONLY_PATTERNS = [
  /\/v1\/robots/,
  /\/v1\/missions/,
  /\/api\//,
  /oauth/,
  /token/,
  /websocket/,
  /ws:\/\//,
  /wss:\/\//,
];

// ── Install ──────────────────────────────────────────────────────────────────
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(SHELL_CACHE)
      .then(async cache => {
        const cortexUrls = await cortexAssetUrls();
        return Promise.allSettled(
          [...SHELL_ASSETS, ...cortexUrls].map(url =>
            cache.add(url).catch(err =>
              console.warn('[PRISM SW] Pre-cache miss:', url, err.message)
            )
          )
        );
      })
      .then(() => self.skipWaiting())
  );
});

// ── Activate ─────────────────────────────────────────────────────────────────
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys
          .filter(k => k !== SHELL_CACHE && k !== DATA_CACHE)
          .map(k => {
            console.log('[PRISM SW] Deleting old cache:', k);
            return caches.delete(k);
          })
      )
    ).then(() => self.clients.claim())
  );
});

// ── Fetch ─────────────────────────────────────────────────────────────────────
self.addEventListener('fetch', event => {
  const { request } = event;
  const url = new URL(request.url);

  if (request.method !== 'GET') return;
  if (NETWORK_ONLY_PATTERNS.some(p => p.test(request.url))) return;
  if (!url.protocol.startsWith('http')) return;

  // App-shell navigations are network-first: cache-first would serve a stale
  // shell forever once cached (the server injects per-tenant config and ships
  // updates in the same file). Cache fallback keeps offline working.
  if (request.mode === 'navigate') {
    event.respondWith(networkFirstShell(request));
    return;
  }

  event.respondWith(cacheFirst(request));
});

async function networkFirstShell(request) {
  try {
    const networkResponse = await fetch(request);
    if (networkResponse.ok) {
      const cache = await caches.open(SHELL_CACHE);
      cache.put(request, networkResponse.clone());
    }
    return networkResponse;
  } catch {
    // ignoreSearch: entry-point URLs (./?source=pwa etc.) must all resolve to
    // the one cached shell instead of each needing its own cached copy.
    const cached = await caches.match(request, { ignoreSearch: true })
      || await caches.match('./PRISM-v10-complete.html')
      || await caches.match('./');
    return cached || new Response(
      '<h1>PRISM is offline</h1><p>Please check your connection.</p>',
      { headers: { 'Content-Type': 'text/html' } }
    );
  }
}

async function cacheFirst(request) {
  const cached = await caches.match(request, { ignoreSearch: false });
  if (cached) return cached;

  try {
    const networkResponse = await fetch(request);

    if (networkResponse.ok || networkResponse.type === 'opaque') {
      const cache = await caches.open(
        request.url.includes(self.location.origin) ? SHELL_CACHE : DATA_CACHE
      );
      cache.put(request, networkResponse.clone());
    }

    return networkResponse;
  } catch {
    if (request.mode === 'navigate') {
      const offlineFallback = await caches.match('./PRISM-v10-complete.html');
      return offlineFallback || new Response(
        '<h1>PRISM is offline</h1><p>Please check your connection.</p>',
        { headers: { 'Content-Type': 'text/html' } }
      );
    }
    return new Response('', { status: 503, statusText: 'Offline' });
  }
}

// ── Message handler ──────────────────────────────────────────────────────────
self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  if (event.data?.type === 'CACHE_INVALIDATE') {
    caches.delete(SHELL_CACHE).then(() => {
      event.ports?.[0]?.postMessage({ ok: true });
    });
  }
});

// ── Push notifications (Phase 1 — F5 PWA alpha) ───────────────────────────────
// Payload shape sent by prism-server/src/services/push.ts:
//   { title, body, data: { code, externalId } }
self.addEventListener('push', event => {
  let payload = { title: 'PRISM', body: 'You have a new alert.' };
  try { if (event.data) payload = Object.assign(payload, event.data.json()); } catch (err) {
    console.warn('[PRISM SW] Push payload parse failed:', err.message);
  }

  event.waitUntil(
    self.registration.showNotification(payload.title, {
      body: payload.body,
      icon: './icon-192.png',
      badge: './icon-192.png',
      tag: (payload.data && payload.data.externalId) || 'prism-alert',
      data: payload.data || {},
    })
  );
});

// Clicking the notification focuses an existing PRISM tab, or opens one.
self.addEventListener('notificationclick', event => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clients => {
      for (const client of clients) {
        if (client.url.includes('PRISM-v10-complete.html') && 'focus' in client) return client.focus();
      }
      if (self.clients.openWindow) return self.clients.openWindow('./PRISM-v10-complete.html');
    })
  );
});
