/* tests/widget.test.ts — drives examples/demo-dashboard/index.html in headless Chromium over http
 * (never file://) and pins CONTRACTS.md §5–§6 + §9 at the DOM: the keyword rung, the status
 * provider, the `need` gate (links are DROPPED, never disabled), the honest fallback, XSS via the
 * one escaper, the ONNX path against a random-weight bundle, sha256 tamper refusal, zero
 * cross-origin requests, and chip → host.navigate.
 */
/// <reference lib="dom" />
import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach } from 'vitest';
import { chromium, type Browser, type Page, type BrowserContext } from 'playwright';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';
import { start, type StaticServer } from './support/static-server.js';

export {};
declare global {
  interface Window { Cortex: any; NORTHWIND: any; __nav: any; __pwned: any; }
}

const PKG = path.resolve(__dirname, '..');
const DEMO_PATH = '/examples/demo-dashboard/index.html';
const MODEL_PREFIX = '/examples/demo-dashboard/cortex/model/';
const RUNTIME_PREFIX = '/runtime/';
const REAL_MODEL_DIR = path.join(PKG, 'examples', 'demo-dashboard', 'cortex', 'model');
// The random-weight ONNX bundle is generated by tests/support/gen-dummy-bundle.py, which needs
// the trainer's Python (torch + onnx). Resolve it from CORTEX_TRAIN_PYTHON, else the package's
// own train/.venv, else `python3`; when none of those can `import torch, onnx` the ONNX block
// is SKIPPED with that reason — never a hard-coded machine path, never a silent pass.
const VENV_PY: string = (() => {
  const fromEnv = process.env.CORTEX_TRAIN_PYTHON;
  if (fromEnv) return fromEnv;
  const local = path.join(PKG, 'train', '.venv', 'bin', 'python');
  return fs.existsSync(local) ? local : 'python3';
})();
const TORCH_AVAILABLE: boolean = (() => {
  const probe = spawnSync(VENV_PY, ['-c', 'import torch, onnx'], { encoding: 'utf8' });
  return probe.status === 0;
})();
if (!TORCH_AVAILABLE) console.warn(`[widget.test] ONNX-path cases skipped: ${VENV_PY} cannot import torch+onnx (set CORTEX_TRAIN_PYTHON)`);
const SCRATCH = process.env.CORTEX_TEST_SCRATCH || fs.mkdtempSync(path.join(os.tmpdir(), 'cortex-widget-'));

// A CI/dev machine may pin one Chromium build under PLAYWRIGHT_BROWSERS_PATH that the installed
// playwright package's revision doesn't match, so resolve the executable ourselves when such a
// directory exists; otherwise (undefined) Playwright uses its own installed browser.
function chromiumExecutable(): string | undefined {
  const root = process.env.PLAYWRIGHT_BROWSERS_PATH || '/opt/pw-browsers';
  if (!fs.existsSync(root)) return undefined;
  const dirs = fs.readdirSync(root).filter((d) => /^chromium-\d+$/.test(d)).sort();
  for (const d of dirs.reverse()) {
    const exe = path.join(root, d, 'chrome-linux', 'chrome');
    if (fs.existsSync(exe)) return exe;
  }
  return undefined;
}

let server: StaticServer;
let browser: Browser;
let context: BrowserContext;
let page: Page;

function runtimeDir(): string {
  const shipped = path.join(PKG, 'runtime');
  if (fs.existsSync(path.join(shipped, 'ort.wasm.min.mjs'))) return shipped;
  return path.join(PKG, 'node_modules', 'onnxruntime-web', 'dist');
}

async function openDemo(p: Page): Promise<void> {
  await p.goto(server.url + DEMO_PATH, { waitUntil: 'load' });
  await p.evaluate(() => window.NORTHWIND.ready);
}
async function ask(p: Page, q: string): Promise<any> {
  return p.evaluate((query) => window.Cortex.ask(query), q);
}
async function openAndWait(p: Page, q: string): Promise<void> {
  await p.evaluate((query) => window.Cortex.open(query), q);
  await p.waitForSelector('#cortex-answer-card', { timeout: 30_000 });
}

describe('widget (browser)', () => {
  beforeAll(async () => {
    server = await start({
      root: PKG,
      mounts: { [RUNTIME_PREFIX]: runtimeDir(), [MODEL_PREFIX]: null },
    });
    browser = await chromium.launch({ executablePath: chromiumExecutable(), headless: true });
  });
  afterAll(async () => {
    if (browser) await browser.close();
    if (server) await server.stop();
  });
  beforeEach(async () => {
    server.mount(MODEL_PREFIX, null); // default: no model served → keyword-only
    context = await browser.newContext({ viewport: { width: 1280, height: 800 } });
    page = await context.newPage();
  });
  afterEach(async () => {
    await context.close();
  });

  it('(a) keyword-only: a howto question resolves on the keyword rung with numbered steps and honest provenance', async () => {
    await openDemo(page);
    const r = await ask(page, 'how do i raise a ticket');
    expect(r.evidence.intent).toBe('create_ticket');
    expect(r.evidence.ladderRung).toBe('keyword');
    expect(r.ladderRung).toBe('keyword');
    expect(r.chips.length).toBeGreaterThan(0);
    expect(r.answerText).toMatch(/^1\. Open Tickets from the top navigation\. 2\. /);
    expect(r.evidence.plannerTemplateId).toBe('planner.howto.create_ticket');

    await openAndWait(page, 'how do i raise a ticket');
    const text = await page.textContent('#cortex-answer .cortex-answer-text');
    expect(text).toContain('1. Open Tickets from the top navigation.');
    expect(text).toContain('2. Click New ticket');
    const prov = await page.textContent('#cortex-prov');
    expect(prov).toMatch(/keyword match/i);
    expect(prov).not.toMatch(/model v\d|confidence \d/i);   // no fabricated model claim
    const chips = await page.$$eval('#cortex-answer button.cortex-chip', (b) => b.map((x) => x.textContent));
    expect(chips).toEqual(['Tickets', 'New ticket']);
    const st = await page.evaluate(() => window.Cortex.state());
    expect(st.modelState).toBe('failed');       // ledger.json 404s in this configuration
    expect(st.modelError).toBeTruthy();
  });

  it('(b) status intent: the number comes from DEMO_STATE, on the keyword rung', async () => {
    await openDemo(page);
    const r = await ask(page, 'how many tickets are open');
    expect(r.evidence.intent).toBe('open_tickets_status');
    expect(r.evidence.ladderRung).toBe('keyword');
    const m = String(r.answerText).match(/\d+/);
    expect(m).not.toBeNull();
    const expected = await page.evaluate(() => window.NORTHWIND.openTickets().length);
    expect(Number(m![0])).toBe(expected);
    expect(expected).toBeGreaterThan(0);

    // A slot-bearing status question filters by the vocab label the keyword rung detected.
    const r2 = await ask(page, 'how many open tickets does Facilities have');
    expect(r2.evidence.intent).toBe('open_tickets_status');
    expect(r2.evidence.registryEntriesUsed).toContain('slot.department:facilities');
    const fac = await page.evaluate(() => window.NORTHWIND.openTickets({ dept: 'Facilities' }).length);
    expect(Number(String(r2.answerText).match(/\d+/)![0])).toBe(fac);

    // An intent the host does not answer gets the registry's honest unavailable copy, never a number.
    await page.evaluate(() => { window.NORTHWIND.host.status = () => undefined; });
    const r3 = await ask(page, 'is everything running');
    expect(r3.evidence.intent).toBe('system_health');
    expect(r3.answerText).toBe("I can't read system health from here — open Status for the live board.");
  });

  it('(c) need gate: with the Viewer role ticked the admin-gated chip is ABSENT from the DOM', async () => {
    await openDemo(page);
    // non-vacuity: the chip is there before the role changes
    await openAndWait(page, 'how do i add a user');
    let users = await page.$$('#cortex-root button.cortex-chip:has-text("Users")');
    expect(users.length).toBe(1);

    await page.evaluate(() => window.Cortex.close());
    await page.check('#viewer-role');
    await page.evaluate(() => { document.getElementById('cortex-answer')!.innerHTML = ''; });
    await openAndWait(page, 'how do i add a user');
    const r = await ask(page, 'how do i add a user');
    expect(r.evidence.intent).toBe('manage_users');
    expect(r.chips).toEqual([]);
    users = await page.$$('#cortex-root button.cortex-chip:has-text("Users")');
    expect(users.length).toBe(0);
    const disabled = await page.$$('#cortex-root button[disabled]');
    expect(disabled.length).toBe(0);     // dropped, never rendered disabled
    const text = await page.textContent('#cortex-answer .cortex-answer-text');
    expect(text).toContain('1. Open Settings → Users.');
  });

  it('(d) fallback: nonsense yields the honest fallback plus the guide list', async () => {
    await openDemo(page);
    const r = await ask(page, 'purple monkey dishwasher');
    expect(r.evidence.ladderRung).toBe('fallback');
    expect(r.evidence.intent).toBeNull();
    expect(r.evidence.plannerTemplateId).toBe('planner.fallback');
    expect(r.chips).toEqual([]);
    expect(r.answerText).toMatch(/not sure what you're asking/i);   // = core FALLBACK_COPY (drift-tested)
    expect(r.answerText).not.toMatch(/\d/);
    // §2.11: out_of_domain has an empty keyword bag — its label words can never win the keyword rung
    const ood = await ask(page, 'something else');
    expect(ood.evidence.ladderRung).toBe('fallback');
    expect(ood.evidence.intent).toBeNull();

    await openAndWait(page, 'purple monkey dishwasher');
    const items = await page.$$('#cortex-guide .cortex-guide-item');
    expect(items.length).toBe(9);          // the nine howto intents in the example registry
    const prov = await page.textContent('#cortex-prov');
    expect(prov).toMatch(/no confident match/i);
    expect(prov).not.toMatch(/model v\d/i);
  });

  it('(e) XSS: a hostile registry label renders as literal text through the escaper', async () => {
    await openDemo(page);
    const payload = '<img src=x onerror=window.__pwned=1>';
    await page.evaluate((label) => {
      return window.Cortex.mount({
        registry: {
          registryVersion: '1',
          app: { slug: 'evil', name: label, assistantName: label },
          slots: {},
          intents: [
            { id: 'zzz_thing', family: 'howto', label, slots: [], keywords: 'zzz', templates: ['zzz'], paraphrases: [],
              answer: { steps: ['Step one ' + label, 'Step two'], links: [{ label, target: { route: '/x' } }] } }
          ]
        },
        host: { navigate() {}, isAllowed() { return true; } },
        ui: { launcher: true }
      });
    }, payload);
    // guide list (fallback) sink
    await openAndWait(page, 'purple monkey dishwasher');
    const guideText = await page.textContent('#cortex-guide');
    expect(guideText).toContain(payload);
    // answer text + chip + header/launcher sinks
    await page.evaluate(() => { document.getElementById('cortex-answer')!.innerHTML = ''; });
    await openAndWait(page, 'zzz please');
    const answerText = await page.textContent('#cortex-answer .cortex-answer-text');
    expect(answerText).toContain('1. Step one ' + payload);
    const chipText = await page.textContent('#cortex-answer button.cortex-chip');
    expect(chipText).toBe(payload);
    expect(await page.textContent('#cortex-title')).toBe(payload);
    expect(await page.textContent('#cortex-launcher')).toBe(payload);

    const imgs = await page.$$('#cortex-root img');
    expect(imgs.length).toBe(0);
    const pwned = await page.evaluate(() => window.__pwned);
    expect(pwned).toBeUndefined();
  });

  it('(i) chip click closes the drawer and calls host.navigate with the registry target', async () => {
    await openDemo(page);
    await page.evaluate(() => {
      const h = window.NORTHWIND.host;
      const orig = h.navigate.bind(h);
      h.navigate = (t: any) => { window.__nav = t; return orig(t); };
    });
    await openAndWait(page, 'how do i raise a ticket');
    await page.click('#cortex-root button.cortex-chip:has-text("New ticket")');
    const nav = await page.evaluate(() => window.__nav);
    expect(nav).toEqual({ route: '/tickets/new' });
    const isOpen = await page.$eval('#cortex-back', (el) => el.classList.contains('cortex-open'));
    expect(isOpen).toBe(false);
    expect(await page.evaluate(() => location.hash)).toBe('#/tickets/new');
    expect(await page.textContent('#page h1')).toBe('New ticket');
  });

  it('drawer chrome: hotkey opens with focus on the input, Escape and backdrop close', async () => {
    await openDemo(page);
    await page.keyboard.press('Control+k');
    expect(await page.$eval('#cortex-back', (el) => el.classList.contains('cortex-open'))).toBe(true);
    expect(await page.evaluate(() => document.activeElement && document.activeElement.id)).toBe('cortex-q');
    await page.keyboard.press('Escape');
    expect(await page.$eval('#cortex-back', (el) => el.classList.contains('cortex-open'))).toBe(false);
    await page.click('#cortex-launcher');
    expect(await page.$eval('#cortex-back', (el) => el.classList.contains('cortex-open'))).toBe(true);
    await page.mouse.click(20, 400); // backdrop, far from the right-side panel
    expect(await page.$eval('#cortex-back', (el) => el.classList.contains('cortex-open'))).toBe(false);
    // every id and class inside the widget carries the cortex- prefix
    const bad = await page.evaluate(() => {
      const out: string[] = [];
      document.querySelectorAll('#cortex-root *').forEach((el: Element) => {
        if (el.id && !el.id.startsWith('cortex-')) out.push('#' + el.id);
        el.classList.forEach((c: string) => { if (!c.startsWith('cortex-')) out.push('.' + c); });
      });
      return out;
    });
    expect(bad).toEqual([]);
  });

  it('server mode: POST serverUrl while host.isLive(), fall back locally (and say so) when it fails', async () => {
    await openDemo(page);
    await page.evaluate(() => {
      const w = window as any;
      w.__serverCalls = [];
      w.__serverMode = 'ok';
      const realFetch = w.fetch.bind(w);
      w.fetch = (input: any, init: any) => {
        const url = String(input);
        if (!url.endsWith('/api/advisor')) return realFetch(input, init);
        w.__serverCalls.push({ url, method: init && init.method, body: init && init.body, headers: init && init.headers });
        if (w.__serverMode === 'down') return Promise.resolve(new Response('nope', { status: 503 }));
        const body = { answer: 'Server says: open Tickets.', chips: [{ label: 'Tickets', target: { route: '/tickets' }, need: 'tickets' }, { label: 'Users', target: { route: '/settings/users' }, need: 'admin' }],
          evidence: { plannerTemplateId: 'planner.howto.create_ticket', registryEntriesUsed: ['intent:create_ticket'], modelSha256: 'abc' },
          intent: 'create_ticket', intentConf: 0.93, ladderRung: 'cortex', modelVersion: '9.9.9' };
        return Promise.resolve(new Response(JSON.stringify(body), { status: 200, headers: { 'Content-Type': 'application/json' } }));
      };
      const opts = Object.assign({}, w.NORTHWIND.mountOpts, { serverUrl: '/api/advisor', modelBase: undefined });
      opts.host = Object.assign({}, w.NORTHWIND.host, { isLive: () => true, headers: () => ({ 'X-Demo-Token': 't1' }) });
      return w.Cortex.mount(opts);
    });
    await page.check('#viewer-role'); // the need gate applies to server chips too
    const r = await ask(page, 'how do i raise a ticket');
    // evidence.ladderRung is the rung the SERVER answered on (§5.4 union), never a widget-invented
    // 'server' value; the transport is reported separately as serverRung.
    expect(r.evidence.ladderRung).toBe('cortex');
    expect(r.serverRung).toBe('cortex');
    expect(r.answerText).toBe('Server says: open Tickets.');
    expect(r.chips.map((c: any) => c.label)).toEqual(['Tickets']);   // admin chip dropped
    expect(r.evidence.modelVersion).toBe('9.9.9');
    expect(r.provenance).toMatch(/answered by the server/i);
    expect(r.provenance).toContain('model v9.9.9');
    const calls = await page.evaluate(() => (window as any).__serverCalls);
    expect(calls.length).toBe(1);
    expect(calls[0].method).toBe('POST');
    expect(JSON.parse(calls[0].body)).toEqual({ query: 'how do i raise a ticket' });
    expect(calls[0].headers['X-Demo-Token']).toBe('t1');
    expect(await page.evaluate(() => window.Cortex.state().mode)).toBe('server');

    await page.evaluate(() => { (window as any).__serverMode = 'down'; });
    const r2 = await ask(page, 'how do i raise a ticket');
    expect(r2.evidence.ladderRung).toBe('keyword');
    expect(r2.evidence.intent).toBe('create_ticket');
    expect(r2.provenance).toMatch(/server could not be reached/i);
    expect(r2.provenance).toMatch(/keyword match/i);
    expect(r2.provenance).not.toContain('9.9.9');
  });

  describe.skipIf(!TORCH_AVAILABLE)('ONNX path (random-weight bundle)', () => {
    const bundleDir = path.join(SCRATCH, 'dummy-model');
    const tamperDir = path.join(SCRATCH, 'dummy-model-tampered');
    let labels: { intents: string[]; slots: string[] };
    let ledger: any;

    beforeAll(() => {
      if (!fs.existsSync(path.join(bundleDir, 'ledger.json'))) {
        const res = spawnSync(VENV_PY, [path.join(PKG, 'tests', 'support', 'gen-dummy-bundle.py'), '--out', bundleDir], { encoding: 'utf8' });
        if (res.status !== 0) throw new Error('gen-dummy-bundle.py failed: ' + res.stderr);
      }
      ledger = JSON.parse(fs.readFileSync(path.join(bundleDir, 'ledger.json'), 'utf8'));
      labels = JSON.parse(fs.readFileSync(path.join(bundleDir, ledger.labels.file), 'utf8'));
      // tampered copy: same files, wrong onnx sha256 in the ledger
      fs.rmSync(tamperDir, { recursive: true, force: true });
      fs.mkdirSync(tamperDir, { recursive: true });
      for (const f of fs.readdirSync(bundleDir)) fs.copyFileSync(path.join(bundleDir, f), path.join(tamperDir, f));
      const bad = JSON.parse(JSON.stringify(ledger));
      bad.onnx.sha256 = '0'.repeat(64);
      fs.writeFileSync(path.join(tamperDir, 'ledger.json'), JSON.stringify(bad, null, 2));
    }, 180_000);

    it('(f) classify() runs the real in-browser model; ask() reports the rung honestly', async () => {
      server.mount(MODEL_PREFIX, bundleDir);
      await openDemo(page);
      const c = await page.evaluate(() => window.Cortex.classify('hello'));
      expect(labels.intents).toContain(c.intent);
      expect(c.intentConf).toBeGreaterThan(0);
      expect(c.intentConf).toBeLessThanOrEqual(1);
      expect(Array.isArray(c.slots)).toBe(true);
      const st = await page.evaluate(() => window.Cortex.state());
      expect(st.modelState).toBe('ready');
      expect(st.modelVersion).toBe(ledger.version);
      expect(st.modelError).toBeNull();

      const r = await ask(page, 'how do i raise a ticket');
      expect(['cortex', 'keyword']).toContain(r.evidence.ladderRung);
      await openAndWait(page, 'how do i raise a ticket');
      const prov = (await page.textContent('#cortex-prov')) || '';
      if (r.evidence.ladderRung === 'cortex') {
        expect(prov).toContain('v' + ledger.version);
        expect(prov).toMatch(/confidence \d+%/);
        expect(r.evidence.modelVersion).toBe(ledger.version);
        expect(r.evidence.modelSha256).toBe(ledger.onnx.sha256);
      } else {
        expect(prov).not.toContain(ledger.version);
        expect(prov).toMatch(/keyword match/i);
        expect(r.evidence.modelVersion).toBeNull();
      }
    }, 60_000);

    it('(h) the whole ONNX flow makes zero cross-origin requests', async () => {
      server.mount(MODEL_PREFIX, bundleDir);
      const urls: string[] = [];
      page.on('request', (req) => urls.push(req.url()));
      await openDemo(page);
      await page.evaluate(() => window.Cortex.classify('hello'));
      await ask(page, 'how do i raise a ticket');
      await openAndWait(page, 'which rooms are free');
      expect(urls.length).toBeGreaterThan(5);
      const foreign = urls.filter((u) => {
        if (u.startsWith('blob:')) return !u.startsWith('blob:' + server.origin + '/');
        try { return new URL(u).origin !== server.origin; } catch { return true; }
      });
      expect(foreign).toEqual([]);
      // the model + runtime were actually fetched from this origin
      expect(urls.some((u) => u.endsWith(MODEL_PREFIX + 'ledger.json'))).toBe(true);
      expect(urls.some((u) => u.includes(RUNTIME_PREFIX + 'ort.wasm.min.mjs'))).toBe(true);
      expect(urls.some((u) => u.endsWith('.wasm'))).toBe(true);
    }, 60_000);

    it('(g) sha256 tamper: classify rejects, ask still answers on the keyword rung, modelError is set', async () => {
      server.mount(MODEL_PREFIX, tamperDir);
      await openDemo(page);
      const err = await page.evaluate(() => window.Cortex.classify('hello').then(() => null, (e: any) => String(e && e.message || e)));
      expect(err).toMatch(/sha256 mismatch/);
      const r = await ask(page, 'how do i raise a ticket');
      expect(r.evidence.ladderRung).toBe('keyword');
      expect(r.evidence.intent).toBe('create_ticket');
      const st = await page.evaluate(() => window.Cortex.state());
      expect(st.modelState).toBe('failed');
      expect(st.modelError).toMatch(/sha256 mismatch/);
      await openAndWait(page, 'how do i raise a ticket');
      const prov = (await page.textContent('#cortex-prov')) || '';
      expect(prov).toMatch(/keyword match/i);
      expect(prov).toMatch(/could not be loaded/i);
      expect(prov).not.toContain(ledger.version);
    }, 60_000);

    it.skipIf(!fs.existsSync(path.join(REAL_MODEL_DIR, 'ledger.json')))(
      'real bundle (when present): classify("how do i raise a ticket") → create_ticket', async () => {
        server.mount(MODEL_PREFIX, REAL_MODEL_DIR);
        await openDemo(page);
        const c = await page.evaluate(() => window.Cortex.classify('how do i raise a ticket'));
        expect(c.intent).toBe('create_ticket');
        expect(c.intentConf).toBeGreaterThan(0);
        expect(c.intentConf).toBeLessThanOrEqual(1);
      }, 60_000);
  });
});
