/**
 * The two built-in meta intents (docs/CONTRACTS.md §1.4). Always part of the taxonomy; a host
 * may declare either one to override its utterance set. Everything here is generic English —
 * nothing app-specific.
 */

import type { NormalizedIntentDef } from './types';

const GREETING_TEMPLATES: string[] = [
  'hello',
  'hi',
  'hey',
  'hi there',
  'hello there',
  'good morning',
  'good afternoon',
  'good evening',
  'morning',
  'evening',
  'howdy',
  'hey assistant',
  'hello assistant',
  'hi assistant',
  'hello again',
  'hi again',
  'thanks',
  'thank you',
  'thanks a lot',
  'thank you very much',
  'cheers',
  'bye',
  'goodbye',
  'see you later',
  'bye for now',
  'have a nice day',
  'good night',
  'nice to meet you',
  'greetings',
  'yo',
];

const GREETING_PARAPHRASES: string[] = [
  'hello, anyone there',
  'hi, are you there',
  'hey, you around',
  'good morning to you',
  'morning, how are you',
  'hi how are you doing',
  'hey how is it going',
  'hello how are you',
  'thanks for the help',
  'thank you for your help',
  'thanks, that is all',
  'ok thanks',
  'great, thanks',
  'perfect, thank you',
  'cheers mate',
  'ok bye',
  'bye bye',
  'see you',
  'catch you later',
  'talk to you later',
  'that is all for now, thanks',
  'good afternoon, how are you',
  'good evening to you',
  'hello and good morning',
  'hiya',
  'hey hey',
  'hi hi',
  'well hello',
  'hello friend',
  'hi, nice to meet you',
];

const OUT_OF_DOMAIN_TEMPLATES: string[] = [
  'what is the weather today',
  'is it going to rain tomorrow',
  'what is the temperature outside',
  'tell me a joke',
  'tell me a funny story',
  'who won the game last night',
  'what is the football score',
  'when is the next world cup',
  'how do i bake a chocolate cake',
  'give me a recipe for pancakes',
  'how long do i boil an egg',
  'what is the capital of france',
  'how tall is mount everest',
  'who wrote hamlet',
  'what is 12 times 17',
  'what is the square root of 144',
  'convert 10 miles to kilometers',
  'translate hello into spanish',
  'how do you say thank you in japanese',
  'what does bonjour mean',
  'sing me a song',
  'write me a poem about the ocean',
  'recommend a good movie',
  'what year did the moon landing happen',
  'how far away is the sun',
  'what is the meaning of life',
  'who is the president of the united states',
  'what time is it in tokyo',
  'play some music',
  'what is the best pizza topping',
];

const OUT_OF_DOMAIN_PARAPHRASES: string[] = [
  'will it be sunny this weekend',
  'do i need an umbrella today',
  'how cold is it in oslo right now',
  'know any good jokes',
  'make me laugh',
  'did my team win yesterday',
  'what was the final score of the match',
  'who is the fastest runner in the world',
  'how do i make a lasagna',
  'what goes into a margarita',
  'how many calories are in a banana',
  'what is the longest river on earth',
  'how many planets are in the solar system',
  'who painted the mona lisa',
  'what is 15 percent of 80',
  'solve 3x plus 5 equals 20',
  'how many ounces in a pound',
  'say good night in italian',
  'what is the french word for cheese',
  'how do you spell necessary',
  'write a haiku about autumn',
  'tell me a bedtime story',
  'what should i watch tonight',
  'when did the berlin wall fall',
  'how old is the universe',
  'what is your favorite color',
  'are you a real person',
  'what is the time in new york',
  'put on some jazz',
  'which is better, cats or dogs',
];

export const BUILTIN_META_INTENTS: Readonly<Record<'greeting' | 'out_of_domain', NormalizedIntentDef>> = {
  greeting: {
    id: 'greeting',
    family: 'meta',
    label: 'Greeting',
    slots: [],
    keywords: 'hello hey greetings thanks thank bye goodbye morning afternoon evening howdy',
    templates: GREETING_TEMPLATES,
    paraphrases: GREETING_PARAPHRASES,
  },
  out_of_domain: {
    id: 'out_of_domain',
    family: 'meta',
    label: 'Something else',
    slots: [],
    keywords: '',
    templates: OUT_OF_DOMAIN_TEMPLATES,
    paraphrases: OUT_OF_DOMAIN_PARAPHRASES,
  },
};

export function builtinIntent(id: 'greeting' | 'out_of_domain'): NormalizedIntentDef {
  const b = BUILTIN_META_INTENTS[id];
  return {
    ...b,
    slots: [...b.slots],
    templates: [...b.templates],
    paraphrases: [...b.paraphrases],
  };
}
